@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbGFyYXZlbGJpcnJhcy1wcm9kdWN0aW9uLnVwLnJhaWx3YXkuYXBwL2FwaS9sb2dpbiIsImlhdCI6MTcwNTA2Nzg2MiwiZXhwIjoxNzA1MDcxNDYyLCJuYmYiOjE3MDUwNjc4NjIsImp0aSI6ImdiT2hHRWFmT2s3SGRKVjUiLCJzdWIiOiIxIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.5jXqTf8lp0PEkz46Px-gaQ5aZpOCnEi8hr1e4w3UupE

#### Registrarse
POST  http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "name":"Jesus",
    "email":"jesquiliche@hotmail.com",
    "password":"1234678"
}

#### Login
POST  http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "email":"admin@test.com",
    "password":"admin_password"
}

#### Logout
POST  http://127.0.0.1:8000/api/logout
Authorization: Bearer {{accessToken}}

#### refresh
POST  http://127.0.0.1:8000/api/refresh
Authorization: Bearer {{accessToken}}


#### Obtener todos los colores
GET http://localhost:8000/api/v1/colores

### Crear color
POST   http://localhost:8000/api/v1/colores
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Rojo"
}

### Obtener color por Id
GET   http://localhost:8000/api/v1/colores/1


### Modificicar color
DELETE   http://localhost:8000/api/v1/colores/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Prueba 2"
}

#### Obtener todos los paises
GET http://localhost:8000/api/v1/paises

#### Obtener pais por su id
GET http://localhost:8000/api/v1/paises/5

### Crear país
POST   http://localhost:8000/api/v1/paises
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Peru"
}

### Modificar  país
PUT   http://localhost:8000/api/v1/paises/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Pais modificado"
}

### Borrando pais
DELETE   http://localhost:8000/api/v1/paises/9
Authorization: Bearer {{accessToken}}


#### Obtener todos los tipos
GET http://localhost:8000/api/v1/tipos

#### Obtener tipo por su id
GET http://localhost:8000/api/v1/tipos/1

### Crear tipo
POST   http://localhost:8000/api/v1/tipos
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Sin alcohol"
}

### Modificar tipo
PATCH    http://localhost:8000/api/v1/tipos/11
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "update_at":"32323323",
    "nombre":"Doble malta",
    "descripcion":"Prueba"
}

### Borrar tipo
DELETE   http://localhost:8000/api/v1/tipos/2
Authorization: Bearer {{accessToken}}

#### Obtener todas las graduaciones
GET http://localhost:8000/api/v1/graduaciones

#### Obtener graduación por su id
GET http://localhost:8000/api/v1/graduaciones/5

### Crear graduación
POST   http://localhost:8000/api/v1/tipos
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Super toxica"
}

### Obtener ripo
GET   http://localhost:8000/api/v1/tipos/1


### Modificar tipo
PUT   http://localhost:8000/api/v1/graduaciones/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Puro alcohol"
}

### Bor6543rar tipo
DELETE   http://localhost:8000/api/v1/graduaciones/1
Authorization: Bearer {{accessToken}}


#### Obtener las cervezas
GET http://localhost:8000/api/v1/cervezas?oferta=0


#### Obtener una cerveza
GET http://localhost:8000/api/v1/cervezas/15

#### Obtener las cervezas
GET http://localhost:8000/api/v1/cervezas?per_page=1&novedad=0&marca=a

#### Crear cerveza
POST   http://localhost:8000/api/v1/cervezas
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Cerveza Voldamm14",
    "descripcion":"La mejor cerveza de españa",
    "color_id":4,
    "graduacion_id":2,
    "tipo_id":1,
    "pais_id":1,
    "novedad":1,
    "oferta":1,
    "precio":0,
    "foto":"imagen",
    "marca":"damm"
}

#### Modificar cerveza
PUT   http://localhost:8000/api/v1/cervezas/14
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Cerveza Voldamm Modificada",
    "descripcion":"La mejor cerveza de españa erer",
    "color_id":4,
    "graduacion_id":2,
    "tipo_id":1,
    "pais_id":1,
    "novedad":1,
    "oferta":1,
    "precio":0,
    "marca":"damm"
}

#### Modificar cerveza
PATCH  http://localhost:8000/api/v1/cervezas/15
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "id": 13,
    "novedad":1,
    "oferta":1,
    "tipo_id": 16,
   
    
}
#### Borrar cerveza
DELETE  http://localhost:8000/api/v1/cervezas/1
Authorization: Bearer {{accessToken}}

#### Obtener cervezas por pais
GET  http://localhost:8000/api/v1/consultaCervezasPorPais

#### Obtener cervezas por pais
GET  http://localhost:8000/api/v1/consultaCervezasPorTipo

#### Obtener cervezas por pais
GET  http://localhost:8000/api/v1/consultaTablas

#### Obtener cervezas por pais
GET  http://localhost:8000/api/v1/consultaDB








